//! Effects: built-in processors that change audio passing through them, and
//! the Insert Chain that runs them in order.

mod auto_pan;
mod auto_wah;
mod beat_repeat;
mod bitcrusher;
mod chain;
mod chorus;
mod clipper;
mod compressor;
mod de_esser;
mod delay;
mod eq;
mod exciter;
mod filter;
mod flanger;
mod freq_shift;
mod gate;
mod haas;
mod limiter;
mod lofi;
mod multiband;
mod params;
mod phaser;
mod pitch_shift;
mod pump;
mod resonator;
mod reverb;
mod ring_mod;
mod saturator;
mod stereo;
mod trance_gate;
mod transient;
mod tremolo;
mod utility;
mod vibrato;
mod vowel;

pub use auto_pan::{AUTO_PAN_PARAMS, AutoPan};
pub use auto_wah::{AUTO_WAH_PARAMS, AutoWah};
pub use beat_repeat::{BEAT_REPEAT_PARAMS, BeatRepeat};
pub use bitcrusher::{BITCRUSHER_PARAMS, Bitcrusher, BitcrusherSettings};
pub use chain::{Effect, EffectKind, InsertChain, MAX_EFFECTS, effect_parameters_json};
pub use chorus::{CHORUS_PARAMS, Chorus, ChorusSettings};
pub use clipper::{CLIPPER_PARAMS, Clipper};
pub use compressor::{COMPRESSOR_PARAMS, Compressor, CompressorSettings};
pub use de_esser::{DE_ESSER_PARAMS, DeEsser};
pub use delay::{DELAY_PARAMS, Delay, DelaySettings};
pub use eq::{EQ_PARAMS, Eq, EqSettings, eq_response_db};
pub use exciter::{EXCITER_PARAMS, Exciter};
pub use filter::{FILTER_PARAMS, Filter, FilterSettings};
pub use flanger::{FLANGER_PARAMS, Flanger};
pub use freq_shift::{FREQ_SHIFT_PARAMS, FrequencyShifter};
pub use gate::{GATE_PARAMS, Gate, GateSettings};
pub use haas::{HAAS_PARAMS, Haas};
pub use limiter::{LIMITER_PARAMS, Limiter, LimiterSettings};
pub use lofi::{LOFI_PARAMS, LoFi};
pub use multiband::{MULTIBAND_PARAMS, Multiband};
pub use params::Settings;
pub use phaser::{PHASER_PARAMS, Phaser, PhaserSettings};
pub use pitch_shift::{PITCH_SHIFT_PARAMS, PitchShifter};
pub use pump::{PUMP_PARAMS, Pump};
pub use resonator::{RESONATOR_PARAMS, Resonator};
pub use reverb::{REVERB_PARAMS, Reverb, ReverbSettings};
pub use ring_mod::{RING_MOD_PARAMS, RingMod};
pub use saturator::{SATURATOR_PARAMS, Saturator, SaturatorSettings};
pub use trance_gate::{TRANCE_GATE_PARAMS, TranceGate};
pub use transient::{TRANSIENT_PARAMS, TransientShaper};
pub use tremolo::{TREMOLO_PARAMS, Tremolo};
pub use utility::{UTILITY_PARAMS, Utility, UtilitySettings};
pub use vibrato::{VIBRATO_PARAMS, Vibrato};
pub use vowel::{VOWEL_PARAMS, Vowel};
