/**
 * The factory presets, mirroring the engine's (`engine/src/instrument/synth/
 * presets.rs`) so the preset picker can list them before the engine has
 * loaded. `synth-params.test.ts` checks the two against each other.
 *
 * Loading a preset copies its settings into the Track's Instrument, where
 * they can then be changed. The musician's own, User Presets, are kept in
 * the Preset library (`preset/preset-library.ts`) and listed alongside these.
 */
import type { SynthSettings } from "./synth-params";

export interface SynthPreset {
  name: string;
  /** One of bass, lead, pad, pluck or keys. */
  category: string;
  /** What it sounds like, for the musician and the Assistant. */
  description: string;
  settings: SynthSettings;
}

/** Every factory preset, in the order the picker lists them. */
export const SYNTH_PRESETS: readonly SynthPreset[] = [
  {
    name: "Sub Bass",
    category: "bass",
    description: "Deep round sine bass with a little grit underneath",
    settings: {
      osc1Wave: "sine",
      osc2Wave: "triangle",
      osc2Detune: -1200,
      oscMix: 0.3,
      filterType: "lowPass",
      cutoffHz: 320,
      resonance: 0.8,
      filterEnvAmount: 1,
      filterAttack: 0.001,
      filterDecay: 0.25,
      filterSustain: 0.3,
      filterRelease: 0.3,
      attack: 0.004,
      decay: 0.3,
      sustain: 0.85,
      release: 0.12,
      lfoTarget: "off",
      lfoRateHz: 5,
      lfoDepth: 0,
      glide: 0.04,
      voices: 1,
      level: 0.9,
    },
  },
  {
    name: "Reese Bass",
    category: "bass",
    description: "Wide detuned saw bass that growls",
    settings: {
      osc1Wave: "saw",
      osc2Wave: "saw",
      osc2Detune: 18,
      oscMix: 0.5,
      filterType: "lowPass",
      cutoffHz: 520,
      resonance: 3,
      filterEnvAmount: 1.5,
      filterAttack: 0.001,
      filterDecay: 0.4,
      filterSustain: 0.25,
      filterRelease: 0.3,
      attack: 0.006,
      decay: 0.4,
      sustain: 0.8,
      release: 0.15,
      lfoTarget: "off",
      lfoRateHz: 5,
      lfoDepth: 0,
      glide: 0,
      voices: 2,
      level: 0.55,
    },
  },
  {
    name: "Saw Lead",
    category: "lead",
    description: "Bright cutting saw lead with a touch of vibrato",
    settings: {
      osc1Wave: "saw",
      osc2Wave: "saw",
      osc2Detune: 9,
      oscMix: 0.45,
      filterType: "lowPass",
      cutoffHz: 4200,
      resonance: 1.4,
      filterEnvAmount: 1,
      filterAttack: 0.001,
      filterDecay: 0.6,
      filterSustain: 0.5,
      filterRelease: 0.3,
      attack: 0.01,
      decay: 0.25,
      sustain: 0.75,
      release: 0.25,
      lfoTarget: "pitch",
      lfoRateHz: 5.5,
      lfoDepth: 0.06,
      glide: 0.03,
      voices: 2,
      level: 0.7,
    },
  },
  {
    name: "Square Lead",
    category: "lead",
    description: "Hollow square lead, dry and direct",
    settings: {
      osc1Wave: "square",
      osc2Wave: "square",
      osc2Detune: -1195,
      oscMix: 0.35,
      filterType: "lowPass",
      cutoffHz: 3000,
      resonance: 2,
      filterEnvAmount: 1.2,
      filterAttack: 0.001,
      filterDecay: 0.35,
      filterSustain: 0.4,
      filterRelease: 0.3,
      attack: 0.006,
      decay: 0.2,
      sustain: 0.7,
      release: 0.2,
      lfoTarget: "off",
      lfoRateHz: 5,
      lfoDepth: 0,
      glide: 0,
      voices: 1,
      level: 0.65,
    },
  },
  {
    name: "Warm Pad",
    category: "pad",
    description: "Slow swelling saw pad that opens as it grows",
    settings: {
      osc1Wave: "saw",
      osc2Wave: "triangle",
      osc2Detune: 12,
      oscMix: 0.5,
      filterType: "lowPass",
      cutoffHz: 700,
      resonance: 0.9,
      filterEnvAmount: 2.2,
      filterAttack: 1.2,
      filterDecay: 2,
      filterSustain: 0.6,
      filterRelease: 1.5,
      attack: 0.9,
      decay: 1.5,
      sustain: 0.8,
      release: 1.4,
      lfoTarget: "off",
      lfoRateHz: 5,
      lfoDepth: 0,
      glide: 0,
      voices: 8,
      level: 0.6,
    },
  },
  {
    name: "Glass Pad",
    category: "pad",
    description: "Airy triangle pad with the filter drifting under it",
    settings: {
      osc1Wave: "triangle",
      osc2Wave: "sine",
      osc2Detune: 1207,
      oscMix: 0.4,
      filterType: "lowPass",
      cutoffHz: 1800,
      resonance: 1.1,
      filterEnvAmount: 1,
      filterAttack: 0.8,
      filterDecay: 2.5,
      filterSustain: 0.5,
      filterRelease: 2,
      attack: 0.6,
      decay: 1.2,
      sustain: 0.75,
      release: 1.8,
      lfoTarget: "filter",
      lfoRateHz: 0.35,
      lfoDepth: 0.12,
      glide: 0,
      voices: 8,
      level: 0.6,
    },
  },
  {
    name: "Synth Pluck",
    category: "pluck",
    description: "Short filtered pluck that falls away fast",
    settings: {
      osc1Wave: "saw",
      osc2Wave: "square",
      osc2Detune: 5,
      oscMix: 0.3,
      filterType: "lowPass",
      cutoffHz: 900,
      resonance: 2.5,
      filterEnvAmount: 3,
      filterAttack: 0.002,
      filterDecay: 0.22,
      filterSustain: 0,
      filterRelease: 0.12,
      attack: 0.002,
      decay: 0.35,
      sustain: 0,
      release: 0.12,
      lfoTarget: "off",
      lfoRateHz: 5,
      lfoDepth: 0,
      glide: 0,
      voices: 8,
      level: 0.8,
    },
  },
  {
    name: "Bell Pluck",
    category: "pluck",
    description: "Bright bell-like pluck an octave wide",
    settings: {
      osc1Wave: "sine",
      osc2Wave: "triangle",
      osc2Detune: 1902,
      oscMix: 0.45,
      filterType: "bandPass",
      cutoffHz: 800,
      resonance: 1.2,
      filterEnvAmount: 1,
      filterAttack: 0.002,
      filterDecay: 0.5,
      filterSustain: 0.1,
      filterRelease: 0.3,
      attack: 0.002,
      decay: 0.8,
      sustain: 0.05,
      release: 0.35,
      lfoTarget: "off",
      lfoRateHz: 5,
      lfoDepth: 0,
      glide: 0,
      voices: 8,
      level: 0.9,
    },
  },
  {
    name: "Electric Keys",
    category: "keys",
    description: "Soft tine-like keys, mellow and playable",
    settings: {
      osc1Wave: "sine",
      osc2Wave: "triangle",
      osc2Detune: 1203,
      oscMix: 0.25,
      filterType: "lowPass",
      cutoffHz: 2000,
      resonance: 0.9,
      filterEnvAmount: 1.5,
      filterAttack: 0.001,
      filterDecay: 0.9,
      filterSustain: 0.25,
      filterRelease: 0.4,
      attack: 0.004,
      decay: 1.1,
      sustain: 0.35,
      release: 0.4,
      lfoTarget: "off",
      lfoRateHz: 5,
      lfoDepth: 0,
      glide: 0,
      voices: 8,
      level: 0.85,
    },
  },
  {
    name: "Tremolo Keys",
    category: "keys",
    description: "Bright keys with the level wobbling underneath",
    settings: {
      osc1Wave: "square",
      osc2Wave: "saw",
      osc2Detune: -8,
      oscMix: 0.4,
      filterType: "lowPass",
      cutoffHz: 2600,
      resonance: 1,
      filterEnvAmount: 0.8,
      filterAttack: 0.001,
      filterDecay: 0.8,
      filterSustain: 0.4,
      filterRelease: 0.3,
      attack: 0.008,
      decay: 0.9,
      sustain: 0.5,
      release: 0.35,
      lfoTarget: "amp",
      lfoRateHz: 5,
      lfoDepth: 0.4,
      glide: 0,
      voices: 8,
      level: 0.7,
    },
  },
];

/** The preset of that name, or undefined. Names are matched exactly. */
export function synthPreset(name: string): SynthPreset | undefined {
  return SYNTH_PRESETS.find((preset) => preset.name === name);
}

/** The preset names, for the Assistant to pick from. */
export function synthPresetNames(): string[] {
  return SYNTH_PRESETS.map((preset) => preset.name);
}
